---
# defaults file for efk
efk_enabled: false

# namespace for efk
efk_namespace: "kube-logging"

# parameters for elasticsearch
efk_es_svc_name: "elasticsearch"
efk_es_replicas: 1
efk_es_image_repo: "{{ elastic_image_repo }}/elasticsearch/elasticsearch"
efk_es_image_tag: "7.16.1"
efk_busybox_image_repo: "busybox"
efk_busybox_image_tag: "1.32.0"
efk_es_volume_size: "50Gi"

# parameters for kibana
efk_kibana_service_type: "ClusterIP"
efk_kibana_replicas: 1
efk_kibana_image_repo: "{{ elastic_image_repo }}/kibana/kibana"
efk_kibana_image_tag: "7.16.1"
efk_gatekeeper_image_repo: "{{ quay_image_repo }}/keycloak/keycloak-gatekeeper"
efk_gatekeeper_image_tag: "10.0.0"
efk_hyperauth_url: hyperauth.{{ custom_domain_name }}
efk_hyperauth_realm: "tmax"
efk_kibana_client_id: "kibana"
efk_kibana_encryption_key: "AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j"

# parameters for fluentd
efk_fluentd_image_repo: "fluent/fluentd-kubernetes-daemonset"
efk_fluentd_image_tag: "v1.4.2-debian-elasticsearch-1.1"
