---
# default value
hypercloud_enabled: false
hypercloud_hpcd_mode: "multi"
hypercloud_hpcd_single_operator_version: "5.0.25.16"
hypercloud_hpcd_multi_operator_version: "5.0.24.0"
hypercloud_hpcd_api_server_version: "5.0.26.3"
hypercloud_hpcd_template_version: "5.0.24.0"
hypercloud_kafka_enabled: "true"
hypercloud_kafka1_addr: "DNS"
hypercloud_kafka2_addr: "DNS"
hypercloud_kafka3_addr: "DNS"

#hypercloud_hpcd_postgres_version: "5.0.0.1"
hypercloud_invitation_token_expired_date: "7days"
